/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mocks from "./mocks";
export * as vendor from "./vendor";
export { Scribe__factory } from "./Scribe__factory";
