/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockDestination } from "./MockDestination";
export type { MockUniswapDestination } from "./MockUniswapDestination";
