/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockChiadoTellorReader } from "./MockChiadoTellorReader";
export type { MockDestination } from "./MockDestination";
export type { MockMessenger } from "./MockMessenger";
export type { MockTellorProxy } from "./MockTellorProxy";
