/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface MockTellorProxyInterface extends utils.Interface {
  functions: {
    "handleTellorData(bytes)": FunctionFragment;
    "scribe()": FunctionFragment;
    "tellor()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "handleTellorData" | "scribe" | "tellor"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "handleTellorData",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "scribe", values?: undefined): string;
  encodeFunctionData(functionFragment: "tellor", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "handleTellorData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "scribe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tellor", data: BytesLike): Result;

  events: {};
}

export interface MockTellorProxy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockTellorProxyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    handleTellorData(
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    scribe(overrides?: CallOverrides): Promise<[string]>;

    tellor(overrides?: CallOverrides): Promise<[string]>;
  };

  handleTellorData(
    _data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  scribe(overrides?: CallOverrides): Promise<string>;

  tellor(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    handleTellorData(
      _data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    scribe(overrides?: CallOverrides): Promise<string>;

    tellor(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    handleTellorData(
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    scribe(overrides?: CallOverrides): Promise<BigNumber>;

    tellor(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    handleTellorData(
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    scribe(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tellor(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
